local Path = require("obsidian.path")
local util = require("obsidian.util")

return {
   -- get_items = function(ctx, done)
   --    local daily_dir = Path.new(Obsidian.dir)
   --
   --    if Obsidian.opts.daily_notes.folder then
   --       daily_dir = daily_dir / Obsidian.opts.daily_notes.folder
   --    elseif Obsidian.opts.notes_subdir then
   --       daily_dir = daily_dir / Obsidian.opts.notes_subdir
   --    end
   --
   --    vim.system({
   --       "rg",
   --       "--files",
   --       "-g",
   --       "*.md",
   --       tostring(daily_dir),
   --    }, { text = true }, function(result)
   --       if result.code ~= 0 and result.stdout == "" then
   --          done({}, result.stderr)
   --          return
   --       end
   --
   --       local items = {}
   --
   --       for file in vim.gsplit(result.stdout or "", "\n", { trimempty = true }) do
   --          local path = Path.new(file)
   --          local date = util.parse_date(path.stem, Obsidian.opts.daily_notes.date_format)
   --
   --          if date then
   --             local timestamp = os.time({
   --                year = date.year,
   --                month = date.month,
   --                day = date.day,
   --                hour = 12,
   --                min = 0,
   --                sec = 0,
   --             })
   --
   --             for _, item in ipairs(ctx.parse_markdown_file(path)) do
   --                -- Explicit agenda markers win. Otherwise inherit date from the daily note.
   --                item.date = item.date or item.scheduled or item.due or timestamp
   --                item.source = "daily"
   --                items[#items + 1] = item
   --             end
   --          end
   --       end
   --
   --       done(items)
   --    end)
   -- end,
}
